<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'SimpleImage\Factory\ImageServiceFactory' => __DIR__ . '/src/SimpleImage/Factory/ImageServiceFactory.php',
  'SimpleImage\Module'                      => __DIR__ . '/src/SimpleImage/Module.php',
  'SimpleImage\Service\ImageService'        => __DIR__ . '/src/SimpleImage/Service/ImageService.php',
  'SimpleImage\View\Helper\Image'           => __DIR__ . '/src/SimpleImage/View/Helper/Image.php',
);
