<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
'SimpleImage\Factory\ImageServiceFactory' => __DIR__ . '/src/Factory/ImageFactory.php',
'SimpleImage\Module'                      => __DIR__ . '/src/Module.php',
'SimpleImage\Image'                       => __DIR__ . '/src/Service/Image.php',
);
