<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
	'SimpleImage\Module'                                                        => __DIR__ . '/Module.php',
// 	'SimpleImage\Image' 														=> __DIR__ . '/src/SimpleImage/Service/Image.php',
	'SimpleImage\View\Helper\Image'                                             => __DIR__ . '/src/SimpleImage/View/Helper/Image.php',
);
