<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
'SimpleImage\SimpleImage'            		 => __DIR__ . '/SimpleImage.php',
'SimpleImage\Module'                       => __DIR__ . '/Module.php',
'SimpleImage\Exception\ExceptionInterface' => __DIR__ . '/Exception/ExceptionInterface.php',
'SimpleImage\Exception\RuntimeException'   => __DIR__ . '/Exception/RuntimeException.php',
);
